---

- name: Install librdkafka development dependencies
  sudo: yes
  apt:
    name=libsasl2-dev
    state=installed
    update_cache=yes
    cache_valid_time=3600
    force=yes

- name: Sync soure from git
  git:
    repo='https://github.com/senior7515/librdkafka.git'
    accept_hostkey=yes
    clone=yes
    dest='{{third_party_dir}}/librdkafka'
    update=yes
    recursive=yes
    version='64cd2ab'
    force=yes

- shell:
    ./configure --CFLAGS="-O2 -DNDEBUG -fPIC" \
    --CXXFLAGS="-O2 -DNDEBUG -fPIC" --prefix="{{cache_dir}}"
  args:
    chdir: '{{third_party_dir}}/librdkafka'
    creates: '{{third_party_dir}}/librdkafka/Makefile.config'

- command: make -j{{ansible_processor_vcpus}} install
  args:
    chdir: '{{third_party_dir}}/librdkafka'
    creates: '{{cache_dir}}/lib/librdkafka.a'
